### ISSUE TITLE
Error during make

### ISSUE THREAD

**Issue by Laanan** [mredaelli/aerc#1]
Hello,

I am getting an error when I try to make Aerc:

`~/go/src/aerc$ make
go build -tags=notmuch make \
        -ldflags "-X main.Prefix=/home/laanan \
        -X main.ShareDir=/home/laanan/home/laanan/go/src/aerc \
        -X main.Version=0.5.2.r36.gc06a2e6-dirty" \
        -o aerc
go: finding module for package -X main.Prefix=/home/laanan      -X main.ShareDir=/home/laanan/home/laanan/go/src/aerc   -X main.Version=0.5.2.r36.gc06a2e6-dirty
panic: path "-X main.Prefix=/home/laanan \t-X main.ShareDir=/home/laanan/home/laanan/go/src/aerc \t-X main.Version=0.5.2.r36.gc06a2e6-dirty" not in error "invalid import path \"-X main.Prefix=/home/laanan \\t-X main.ShareDir=/home/laanan/home/laanan/go/src/aerc \\t-X main.Version=0.5.2.r36.gc06a2e6-dirty\""

goroutine 1 [running]:
cmd/go/internal/load.ImportErrorf(0x7ffed70755c3, 0x7c, 0xa44910, 0x16, 0xc0001f1548, 0x1, 0x1, 0x0, 0x0)
        /usr/local/go/src/cmd/go/internal/load/pkg.go:445 +0x265
cmd/go/internal/load.(*Package).load(0xc000125680, 0x7ffed70755c3, 0x7c, 0xc0001f1988, 0x0, 0x0, 0x0, 0xc000118000, 0xb05260, 0xc0002fa320)
        /usr/local/go/src/cmd/go/internal/load/pkg.go:1759 +0x97d
cmd/go/internal/load.loadImport(0xc0002fa690, 0x7ffed70755c3, 0x7c, 0xc000026424, 0x18, 0x0, 0xc0001f1988, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/cmd/go/internal/load/pkg.go:658 +0xd2f
cmd/go/internal/load.PackagesAndErrors(0xc000132030, 0x5, 0x5, 0x0, 0x0, 0x0)
        /usr/local/go/src/cmd/go/internal/load/pkg.go:2172 +0x679
cmd/go/internal/load.PackagesForBuild(0xc000132030, 0x5, 0x5, 0xa38d48, 0x2, 0x8)
        /usr/local/go/src/cmd/go/internal/load/pkg.go:2237 +0x5d
cmd/go/internal/work.runBuild(0xdcbae0, 0xc000132030, 0x5, 0x5)
        /usr/local/go/src/cmd/go/internal/work/build.go:351 +0x88
main.main()
        /usr/local/go/src/cmd/go/main.go:190 +0x58d
Makefile:25: recipe for target 'aerc' failed
make: *** [aerc] Error 2
`
Any help/advice you can give would be greatly appreciated -- I'd love to check out this awesome program!

**Comment by mredaelli** [comment]
Hey. This is just a fork for a couple of old experiments of mine. I suggest you try again with the official and up-to-date repo, here: https://git.sr.ht/~sircmpwn/aerc

**Comment by Laanan** [comment]
Hi there,

Thanks so much for getting back to me. The problem was actually
with my golang and GCC packages. I fixed golang, and I got GCC partially 
fixed, but it still can't figure out how to locate cc1, so it can't
compile anything. I've even tried reinstalling the build-essential
package!!!

In any case, I got it working by compiling it on a different computer
and then copying all the files over to this one. Thanks so much for the
cool program!

A couple of questions:

1) Is it possible to *easily* change the editor used during the compose
mode? I'd like to use one that uses Markdown, if possible.

2) Is there an API? One thing I'd like to try and replicate is a
"snooze" function, like on Gmail, to be able to move messages into an
interim folder, and then back into the inbox after a certain amount of
time. I've implemented a similar script in python using the "at" shell
command to handle the scheduling. Is it possible to use shell commands
to change the folder of a message? Like, my idea would be like a command called "snooze," which would move the message to the folder snoozed, set the "at" job (based on user input) via the "pipe" command, which would then run the "move" command at a later time/date to plop the email back into the inbox. Does seem like something that could be done? 

Anyhow, thanks again for the cool command!

Best,

Matt

**Comment by mredaelli** [comment]
Let me reiterate: I definitely am *not* the author of this software. I just wanted to tinker with it, then abandoned the tinkering (mostly for dislike of Go).

For the editor, I'd say you can simply set the `EDITOR` environment variable to the editor you want. If you want to convert Markdown to HTML and make it an HTML email, though, I can't help.

For scripting, take a look at [macros](https://man.archlinux.org/man/aerc-config.5.en#BINDS.CONF) and at the available [commands](https://man.archlinux.org/man/aerc.1.en#RUNTIME_COMMANDS)

**Comment by Laanan** [comment]
Hi, thanks for the ideas, and sorry I got that all confused! I'll check
out those macros and commands. Thank you for the help!
